fixed mosh with command

diff --git a/moshrc b/moshrc
--- a/moshrc
+++ b/moshrc
@@ -14,7 +14,7 @@ function moshrc() {
             echo >&2 $'.sshrc.d and .sshrc files must be less than 64kb\ncurrent size: '$SIZE' bytes'
             exit 1
         fi
-        mosh "$@" -- /bin/bash -c "
+        mosh $MOSHARGS "$DOMAIN" -- /bin/bash -c "
             command -v xxd >/dev/null 2>&1 || { echo >&2 \"sshrc requires xxd to be installed on the server, but it's not. Aborting.\"; exit 1; }
             if [ -e /etc/motd ]; then cat /etc/motd; fi
             if [ -e /etc/update-motd.d ]; then run-parts /etc/update-motd.d/; fi
@@ -47,15 +47,41 @@ EOF
 
             echo $'$(tar czf - -h -C $SSHHOME $files | xxd -p)' | xxd -p -r | tar mxzf - -C \$SSHHOME
             export SSHHOME=\$SSHHOME
-            bash --rcfile \$SSHHOME/sshrc.bashrc
+            if [ -z \"$CMDARGS\" ];then
+              bash --rcfile \$SSHHOME/sshrc.bashrc
+            else
+              bash --rcfile \$SSHHOME/sshrc.bashrc -c \"$CMDARGS\"
+            fi
             "
     else
         echo "No such file: $SSHHOME/.sshrc"
     fi
 }
-if [ "$1" ]; then
-    command -v xxd >/dev/null 2>&1 || { echo >&2 "sshrc requires xxd to be installed locally, but it's not. Aborting."; exit 1; }
-    moshrc "$@"
-else
-    ssh
-fi
+
+function moshrc_parse() {
+  while [[ -n $1 ]]; do
+    case $1 in
+      -p )
+        MOSHARGS="$MOSHARGS $1 $2"; shift ;;
+      -* )
+        MOSHARGS="$MOSHARGS $1" ;;
+      *)
+        if [ -z "$DOMAIN" ]; then
+         DOMAIN="$1"
+        else
+          CMDARGS="$*"
+          return;
+        fi
+        ;;
+    esac
+    shift
+  done
+  if [ -z "$DOMAIN" ]; then
+    mosh $MOSHARGS; exit 1;
+  fi
+}
+
+command -v xxd >/dev/null 2>&1 || { echo >&2 "moshrc requires xxd to be installed locally, but it's not. Aborting."; exit 1; }
+
+moshrc_parse "$@"
+moshrc
